FREQ_DB = [
    {"range": (0.53, 1.71), "label": "AM-радио", "mod": "AM", "usage": "Гражданское вещание"},
    {"range": (26.965, 27.405), "label": "CB (гражданский диапазон)", "mod": "AM/FM", "usage": "Гражданская радиосвязь"},
    {"range": (28, 29.7), "label": "Радиолюбители (10 м)", "mod": "SSB, FM, CW", "usage": "Ham radio"},
    {"range": (50, 54), "label": "Радиолюбители (6 м)", "mod": "SSB, FM, CW", "usage": "Ham radio"},
    {"range": (70, 70.5), "label": "Радиолюбители (4 м)", "mod": "FM, SSB", "usage": "Ham radio"},
    {"range": (88, 108), "label": "FM-радио", "mod": "FM", "usage": "Гражданское вещание"},
    {"range": (118, 137), "label": "Авиасвязь", "mod": "AM", "usage": "Связь с воздушными судами"},
    {"range": (144, 148), "label": "Радиолюбители (2 м)", "mod": "FM, SSB", "usage": "Ham radio"},
    {"range": (430, 440), "label": "Радиолюбители (70 см)", "mod": "FM, SSB", "usage": "Ham radio"},
    {"range": (433.05, 434.79), "label": "ISM 433 МГц", "mod": "FSK, LoRa", "usage": "Датчики, IoT"},
    {"range": (446, 446.2), "label": "PMR446", "mod": "FM", "usage": "Безлицензионная радиосвязь"},
    {"range": (868, 870), "label": "ISM 868 МГц", "mod": "LoRa, FSK", "usage": "Европейская IoT-связь"},
    {"range": (890, 915), "label": "GSM 900 (uplink)", "mod": "GMSK", "usage": "Сотовая связь"},
    {"range": (935, 960), "label": "GSM 900 (downlink)", "mod": "GMSK", "usage": "Сотовая связь"},
    {"range": (1710, 1785), "label": "GSM 1800 (uplink)", "mod": "GMSK", "usage": "Сотовая связь"},
    {"range": (1805, 1880), "label": "GSM 1800 (downlink)", "mod": "GMSK", "usage": "Сотовая связь"},
    {"range": (1920, 1980), "label": "UMTS uplink", "mod": "QPSK", "usage": "3G мобильная связь"},
    {"range": (2110, 2170), "label": "UMTS downlink", "mod": "QPSK", "usage": "3G мобильная связь"},
    {"range": (2400, 2483.5), "label": "Wi‑Fi / Bluetooth / ZigBee", "mod": "OFDM, GFSK", "usage": "Беспроводная связь"},
    {"range": (3400, 3800), "label": "5G NR (n78)", "mod": "QAM, OFDM", "usage": "Мобильная связь 5G"},
    {"range": (5150, 5850), "label": "Wi‑Fi 5 ГГц", "mod": "OFDM", "usage": "Беспроводная связь"},
    {"range": (1575.42, 1575.42), "label": "GPS L1", "mod": "DSSS", "usage": "Навигация (GPS)"},
    {"range": (1602, 1602), "label": "GLONASS L1", "mod": "DSSS", "usage": "Навигация (GLONASS)"},
]